### ISSUE TITLE
NoSuchMethodError: net.kyori.text.serializer.legacy.LegacyComponentSerializer

### ISSUE THREAD

**Issue by Magi1053** [bloodmc/GriefDefender#148]
Using Paper 1.15.2 and GD 1.2.5c
```
Error occurred while enabling GriefDefender v1.2.5 (Is it up to date?)
java.lang.NoSuchMethodError: net.kyori.text.serializer.legacy.LegacyComponentSerializer.legacy()Lnet/kyori/text/serializer/legacy/LegacyComponentSerializer;
	at com.griefdefender.configuration.MessageDataConfig.getMessage(MessageDataConfig.java:67) ~[?:?]
	at com.griefdefender.configuration.MessageDataConfig.getMessage(MessageDataConfig.java:49) ~[?:?]
	at com.griefdefender.cache.MessageCache.loadCache(MessageCache.java:422) ~[?:?]
	at com.griefdefender.GriefDefenderPlugin.loadConfig(GriefDefenderPlugin.java:864) ~[?:?]
	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:434) ~[?:?]
	at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:122) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[GriefDefender] Disabling GriefDefender v1.2.5
```

**Comment by clienthax** [comment]
If you are using spark, update it to the latest one.

**Comment by DrWurzeli** [comment]
if you dont, check for other plugins that use Kyori. this message appears if another plugin is using an outdated Kyori libary, which conflicts with GD since GD is using the latest and greatest one.
