### ISSUE TITLE
SpongeForge Server + GD not working.

### ISSUE THREAD

**Issue by idnthvn** [bloodmc/GriefDefender#160]
Minecraft 1.12.2
Sponge Forge: 7.2.0
Forge 2847
GriefDefender 1.2.6 Sponge B4

Removed Grief Prevention.
Added Grief Defender.
Booted server. It starts but throws errors.
Config stays blank in the GriefDefender folder.

Log is here
```[20:52:49] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task griefdefender-S-7 owned by Plugin{id=griefdefender, name=GriefDefender, version=1.2.6, description=Designed to defend servers from all forms of grief., url=https://github.com/bloodmc/GriefDefender, authors=[bloodmc], source=C:\Program Files (x86)\AT Launcher\servers\IndustrialBox\.\mods\plugins\griefdefender-sponge-1.2.6-B4.jar}, but an error occured.
java.lang.NullPointerException: null
	at com.griefdefender.task.PlayerTickTask.run(PlayerTickTask.java:60) ~[PlayerTickTask.class:1.2.6]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.2.0]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.2.0]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.2.0]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.2.0]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.2.0]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_241]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.2.0]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.2.0]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.2.0]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:457) [SpongeMod.class:1.12.2-2838-7.2.0]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_368_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]```
Please help

**Comment by idnthvn** [comment]
renaming sponge to a_spongeversion, i get this
https://hastebin.com/elahexewor.md
Both way's the config does not load.

**Comment by SnowBlitzz** [comment]
Make sure you've also updated your Luckperms to latest

**Comment by idnthvn** [comment]
Well i had version 5.0.70  and see that 5.0.117 is the newest.   i updated, but the error is still the same

**Comment by idnthvn** [comment]
So the issue is Prism Plugin from Sponge.   Took some removing. But it does not play good with Prism. Unsure what servers are using that are close to prism, but we use it for anyone who griefs

**Comment by kencinder** [comment]
> So the issue is Prism Plugin from Sponge. Took some removing. But it does not play good with Prism. Unsure what servers are using that are close to prism, but **we use it for anyone who griefs**

Not sure what purpose a rollback plugin serves when using **Grief**Defender, but either way it's not related to GD.
However GD *does* have [restore](https://github.com/bloodmc/GriefDefender/wiki/Global-Config#claims) features

**Comment by idnthvn** [comment]
I did not know that GD does that. :) Good to know

**Comment by bloodmc** [comment]
Just tested latest build from https://github.com/prism/Prism/releases and it works fine on latest SF.

**Comment by KLUnknOwN** [comment]
Hello, My players cant seem to use the golden shovel, and somehow i lost all perms to be able to use /gd commands. How can i fix these two issues?
