### ISSUE TITLE
Error with pixelevent

### ISSUE THREAD

**Issue by imartinezgregori** [bloodmc/GriefDefender#216]
When execute a command of pixelevent, grief prevention do that error:
[02:33:50] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'pixelevent:pea start' for source EntityPlayerMP['RocoGamer'/39917, l='world', x=-254.33, y=81.00, z=1674.24]: java.lang.NoClassDefFoundError: me/ryanhamshire/griefprevention/GriefPrevention
java.lang.RuntimeException: java.lang.NoClassDefFoundError: me/ryanhamshire/griefprevention/GriefPrevention
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:165) ~[MinecraftCommandWrapper.class:1.12.2-2838-7.2.1-RC4013]
        at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:146) ~[MinecraftCommandWrapper.class:1.12.2-2838-7.2.1-RC4013]
        at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.2.1-RC4013]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.2.1-RC4013]
        at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.2.1-RC4013]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zld000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.2.1-RC4013]
        at net.minecraft.server.MinecraftServer.redirect$zjh000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoClassDefFoundError: me/ryanhamshire/griefprevention/GriefPrevention
        at fr.flashback083.pixelevent.commands.PixelEventCmdAdmin.execute(PixelEventCmdAdmin.java:113) ~[PixelEventCmdAdmin.class:?]
        at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) ~[bj.class:?]
        at net.minecraft.command.CommandHandler.accessor$tryExecuteCommand(CommandHandler.java) ~[bj.class:?]
        at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:161) ~[MinecraftCommandWrapper.class:1.12.2-2838-7.2.1-RC4013]
        ... 21 more

**Comment by bloodmc** [comment]
This github is for GriefDefender, not GriefPrevention.

**Comment by imartinezgregori** [comment]
This bug is on GriefDefender

**Comment by imartinezgregori** [comment]
![image](https://user-images.githubusercontent.com/50220027/82831871-dcdf9500-9eb9-11ea-9027-be9808e7efdc.png)

**Comment by bloodmc** [comment]
No it is not. PixelEvent is using GP API. Go blame them.

**Comment by Flashback083** [comment]
Hey, contact me on discord Flashback083#1995 i'll try to help you to fix this bug
Latest version of Pixelevent support both GP and GD
