### ISSUE TITLE
Unable to pass event GroupDataRecalculateEvent

### ISSUE THREAD

**Issue by TakoidGit** [bloodmc/GriefDefender#22]
```
[17:18:40 WARN]: [LuckPerms] Unable to pass event GroupDataRecalculateEvent to handler com.griefdefender.listener.LuckPermsEventHandler$$Lambda$2958/296012434
[17:18:40 WARN]: java.lang.ClassCastException: com.griefdefender.permission.GDPermissionHolder cannot be cast to com.griefdefender.permission.GDPermissionGroup
[17:18:40 WARN]:        at com.griefdefender.cache.PermissionHolderCache.getOrCreateGroup(PermissionHolderCache.java:98)
[17:18:40 WARN]:        at com.griefdefender.listener.LuckPermsEventHandler.onGroupDataRecalculate(LuckPermsEventHandler.java:45)
[17:18:40 WARN]:        at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
[17:18:40 WARN]:        at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
[17:18:40 WARN]:        at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
[17:18:40 WARN]:        at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
[17:18:40 WARN]:        at me.lucko.luckperms.common.event.EventFactory.post(EventFactory.java:112)
[17:18:40 WARN]:        at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:125)
[17:18:40 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:106)
[17:18:40 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:18:40 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Happened after entering the command: 
``
/gd flag group default interact-block-primary dragon_egg false
``

Seems to happen when I change GD permissions in LuckPerms and apply them.

**Comment by bloodmc** [comment]
Fixed in 1.2.0 release.
