### ISSUE TITLE
[ACF] Exception in command: gd:pagination

### ISSUE THREAD

**Issue by tak-dev** [bloodmc/GriefDefender#25]
```
[18:27:34] [Server thread/INFO]: takoid issued server command: /gd:pagination dd036a8e-20f6-48ea-86ca-92e75b70c71a next
[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] Exception in command: gd:pagination dd036a8e-20f6-48ea-86ca-92e75b70c71a next
[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] java.lang.reflect.InvocationTargetException

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:576)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.BaseCommand.execute(BaseCommand.java:512)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.RootCommand.execute(RootCommand.java:99)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:79)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] Caused by: com.griefdefender.command.CommandException: Page 4 is greater than the max of 3!

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at com.griefdefender.internal.pagination.ListPagination.getLines(ListPagination.java:89)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at com.griefdefender.internal.pagination.ActivePagination.specificPage(ActivePagination.java:150)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at com.griefdefender.internal.pagination.ActivePagination.nextPage(ActivePagination.java:117)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	at com.griefdefender.command.CommandPagination.execute(CommandPagination.java:29)

[18:27:34] [Server thread/ERROR]: [GriefDefender] [ACF] 	... 25 more
```

First time I got this one. Was just going through the /cf menu in-game.

**Comment by lurr** [comment]
Reproducible by selecting ADVANCED, going to the last page, and then selecting PRESET.
Can also be triggered by scrolling up and triggering gd:callback again when on last page.
