### ISSUE TITLE
Could not pass event BlockPhysicsEvent NPE

### ISSUE THREAD

**Issue by TakoidGit** [bloodmc/GriefDefender#27]
```
[00:24:36 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to the plugin GriefDefender(Look for errors above this in the logs) (TimingIdentifier{id=GriefDefender:onBlockNotify} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-158]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-158]
        at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[patched_1.14.4.jar:git-Paper-158]
        at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[patched_1.14.4.jar:git-Paper-158]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[patched_1.14.4.jar:git-Paper-158]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-158]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.a(World.java:641) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.applyPhysics(World.java:597) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.update(World.java:587) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.notifyAndUpdatePhysics(World.java:501) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.setTypeAndData(World.java:473) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.a(World.java:538) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:345) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:261) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:235) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1134) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-158]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[00:24:36 ERROR]: Could not pass event BlockPhysicsEvent to GriefDefender v1.1.0
java.lang.NullPointerException: null
        at com.griefdefender.listener.BlockEventHandler.onBlockNotify(BlockEventHandler.java:391) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-158]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-158]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-158]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.a(World.java:641) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.applyPhysics(World.java:597) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.update(World.java:587) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.notifyAndUpdatePhysics(World.java:501) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.setTypeAndData(World.java:473) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.World.a(World.java:538) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:345) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:261) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:235) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1134) ~[patched_1.14.4.jar:git-Paper-158]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-158]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by bloodmc** [comment]
Fixed in 1.2.0 release.
