### ISSUE TITLE
NPE Error spams console

### ISSUE THREAD

**Issue by Scorpionvssub** [bloodmc/GriefDefender#285]
`> [16:42:18] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to GriefDefender v1.5.2
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-17d78db-2577f9b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-17d78db-2577f9b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-17d78db-2577f9b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.TileEntityHopper.k(TileEntityHopper.java:199) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.TileEntityHopper.a(TileEntityHopper.java:135) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.TileEntityHopper.tick(TileEntityHopper.java:117) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.World.tickBlockEntities(World.java:643) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:418) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[server.jar:git-Spigot-17d78db-2577f9b]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-17d78db-2577f9b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException`

Unsure what happend but its a lot of spam

**Comment by Scorpionvssub** [comment]
Add-on Info: 
![image](https://user-images.githubusercontent.com/12249763/94467372-21aa6e00-01c3-11eb-9e98-9caa64b663ca.png)

When this is full and items are still trying to go through but cant, it causes the error to popup

**Comment by bloodmc** [comment]
Is this a rented claim? This event should only be processed in rented claims.

**Comment by Scorpionvssub** [comment]
@bloodmc no its a normal /claim and it spams soo much the logs turn into a simple npe but hang on

**Comment by Scorpionvssub** [comment]
[21:22:43 ERROR]: Could not pass event InventoryMoveItemEvent to GriefDefender v1.5.2
java.lang.NullPointerException: null
at com.griefdefender.storage.BaseStorage.getClaimAt(BaseStorage.java:282) ~[?:?]
at com.griefdefender.listener.BlockEventHandler.onInventoryMoveItemEvent(BlockEventHandler.java:131) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-206]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.TileEntityHopper.callPushMoveEvent(TileEntityHopper.java:265) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.TileEntityHopper.hopperPush(TileEntityHopper.java:193) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.TileEntityHopper.k(TileEntityHopper.java:336) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.TileEntityHopper.a(TileEntityHopper.java:135) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.TileEntityHopper.tick(TileEntityHopper.java:117) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.World.tickBlockEntities(World.java:803) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:563) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[21:22:43 ERROR]: Could not pass event InventoryMoveItemEvent to GriefDefender v1.5.2
