### ISSUE TITLE
GD error

### ISSUE THREAD

**Issue by vilper** [bloodmc/GriefDefender#295]
Console says me this: 
[22:04:13] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task griefdefender-S-10 owned by Plugin{id=griefdefender, name=GriefDefender, version=1.2.4, description=This plugin is designed to prevent all forms of grief., url=https://github.com/bloodmc/GriefDefender, authors=[bloodmc], source=./mods/griefdefender-sponge-1.2.4-B5.jar}, but an error occured.
java.lang.NullPointerException: null
        at com.griefdefender.task.PlayerTickTask.run(PlayerTickTask.java:60) ~[PlayerTickTask.class:1.2.4]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.3.0]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_261]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.3.0]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:441) [SpongeMod.class:1.12.2-2838-7.3.0]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]

And I dont know what to do, please, help

**Comment by kencinder** [comment]
[
![image](https://user-images.githubusercontent.com/3614897/97067997-dacd4f80-1599-11eb-9c37-595b0ab1b9aa.png)
](url)

Nothing changed since I told you this yesterday

**Comment by vilper** [comment]
> [ ![image](https://user-images.githubusercontent.com/3614897/97067997-dacd4f80-1599-11eb-9c37-595b0ab1b9aa.png) ](url)
> 
> Nothing changed since I told you this yesterday

I posted this before you told me that sry xD
