### ISSUE TITLE
Creating Subdivisions with "worldedit we" not working on newer sponge versions.

### ISSUE THREAD

**Issue by color-space** [bloodmc/GriefDefender#297]
Title says it all.

***

### Steps to reproduce

1. Create main Claim
2. Select smaller area inside with worldedit
3. /gd mode subdivide
4. /gd claim worldedit we
5. Experience Error "I'm sorry, but there was an error performing this command."

Worldedit used: **worldedit-forge-mc1.12.2-6.1.10-dist.jar**
Luckperms used: **LuckPerms-Sponge-5.2.20.jar**
Griefdefender used: **griefdefender-sponge-1.5.2.jar**
Sponge used: **spongeforge-1.12.2-2838-7.3.1-RC4079.jar**
Forge used: **forge-1.12.2-14.23.5.2838-universal.jar**

***

### Error in Console 

Better formatting: https://hastebin.com/walucutoce.md

```
[00:33:03] [Server thread/INFO] [nucleus]: colorspace_ ran the command: /gd mode subdivide
[00:33:11] [Server thread/INFO] [nucleus]: colorspace_ ran the command: /gd claim worldedit we
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF] Exception in command: claimwe
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF] java.lang.reflect.InvocationTargetException
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at java.lang.reflect.Method.invoke(Method.java:498)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:576)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at co.aikar.commands.BaseCommand.execute(BaseCommand.java:512)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at co.aikar.commands.SpongeRootCommand.executeSponge(SpongeRootCommand.java:96)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at co.aikar.commands.SpongeRootCommand.process(SpongeRootCommand.java:64)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.network.PacketThreadUtil$1.redirect$zlf000$impl$redirectToPhaseTracker(SourceFile:540)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.util.Util.func_181617_a(SourceFile:529)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:325)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.server.MinecraftServer.redirect$zjj000$onRun(MinecraftServer.java:4682)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at java.lang.Thread.run(Thread.java:823)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF] Caused by: java.lang.NullPointerException
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at com.griefdefender.claim.GDClaim$ClaimBuilder.build(GDClaim.java:2860)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at com.griefdefender.internal.provider.GDWorldEditProvider.createClaim(GDWorldEditProvider.java:398)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         at com.griefdefender.command.CommandClaimWorldEdit.execute(CommandClaimWorldEdit.java:50)
[00:33:11] [Server thread/ERROR] [griefdefender]: [ACF]         ... 30 more

```

**Comment by kencinder** [comment]
Tested this too, only with newer Spongeforge, it doesn't matter what parent claim type is, subdivision at all using worldedit selection causes this error.

**Comment by color-space** [comment]
Thanks for the testing/clarification! 
I adjusted title and issue
