### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CJYKK** [bloodmc/GriefDefender#330]
- **Versions**
Spigot/Paper/Sponge: Sponge
Sponge version: 1.12.2-7.3.0
GriefDefender: 1.12.2-4.3.0.692
LuckPerms: v5.2.54

- **Describe the bug**

Failed to load properly.

- **Steps to reproduce the behavior**

1.Put the plugin into the mod folder.
2.Start the server.
3.The plugin crashed.

- **Expected behavior**

The plugin is loaded normally and can be used.

- **GDDEBUG**

- **Screenshots**

![78735d48a20068909a5b1bd043a6c1b](https://user-images.githubusercontent.com/59359590/102013400-e9aad400-3d8a-11eb-8a8d-04f49dd89a93.png)
![b3e982332152b1f31829ad2fdc0048a](https://user-images.githubusercontent.com/59359590/102013402-ec0d2e00-3d8a-11eb-8743-36998e71af44.png)

- **Report errors**
[21:11:08 ERROR] [Sponge]: Could not pass GameAboutToStartServerEvent$Impl to Plugin{id=griefprevention, name=GriefPrevention, version=1.12.2-4.3.0.692, description=This plugin is designed to prevent all forms of grief., url=https://github.com/MinecraftPortCentral/GriefPrevention, source=mods\[领地插件]griefprevention-1.12.2-4.3.0.692.jar}
java.lang.NoClassDefFoundError: io/github/nucleuspowered/nucleus/api/exceptions/PluginAlreadyRegisteredException
        at me.ryanhamshire.griefprevention.GriefPreventionPlugin.onServerAboutToStart(GriefPreventionPlugin.java:757) ~[GriefPreventionPlugin.class:1.12.2-4.3.0.692]
        at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_GriefPreventionPlugin_onServerAboutToStart5.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97) ~[RegisteredListener.class:1.12.2-7.3.0]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:435) ~[SpongeEventManager.class:1.12.2-7.3.0]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:480) ~[SpongeEventManager.class:1.12.2-7.3.0]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255) ~[SpongeImpl.class:1.12.2-7.3.0]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:263) ~[SpongeImpl.class:1.12.2-7.3.0]
        at org.spongepowered.server.SpongeVanilla.onServerAboutToStart(SpongeVanilla.java:171) ~[SpongeVanilla.class:1.12.2-7.3.0]
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpc000$vanilla$callServerAboutToStart(SourceFile:2263) ~[nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:226) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: io.github.nucleuspowered.nucleus.api.exceptions.PluginAlreadyRegisteredException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 12 more
Caused by: java.lang.NullPointerException

**Comment by 02Miki** [comment]
You are using griefprevention not defender
{id=griefprevention, name=GriefPrevention

**Comment by bloodmc** [comment]
As Miki stated, you are not using GriefDefender.

**Comment by CJYKK** [comment]
OMG... Just delete this issue please...
