### ISSUE TITLE
[BUG]zh_CN  loading error

### ISSUE THREAD

**Issue by D-Jy-lab** [bloodmc/GriefDefender#368]
- **Versions**
Spigot/Paper/Sponge: Paper 1.16.5
GriefDefender: 1.5.10
LuckPerms: 5.2.99

- **Describe the bug**
The plug-in cannot run after changing the language to zh_CN.

- **Steps to reproduce the behavior**
plugins/GriefDefender/global.conf
line 260
         -locale="en_US"
         +locale="zh_CN"

- **Expected behavior**
[16:05:44] [Server thread/INFO]: [GriefDefender] Enabling GriefDefender v1.5.10
[16:05:44] [Server thread/INFO]: [GriefDefender] Loading libraries...
[16:05:44] [Server thread/INFO]: [GriefDefender] GriefDefender boot start.
[16:05:45] [Server thread/INFO]: [GriefDefender] Loading configuration...
[16:05:45] [Server thread/ERROR]: [GriefDefender] Failed to load configuration
java.io.IOException: com.griefdefender.lib.typesafe.config.ConfigException$Parse: Reader: 169: Expecting a value but got wrong token: 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) (if you intended 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.griefdefender.lib.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:146) ~[?:?]
	at com.griefdefender.configuration.MessageStorage.reload(MessageStorage.java:453) ~[?:?]
	at com.griefdefender.configuration.MessageStorage.<init>(MessageStorage.java:430) ~[?:?]
	at com.griefdefender.GriefDefenderPlugin.loadConfig(GriefDefenderPlugin.java:1148) ~[?:?]
	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:570) ~[?:?]
	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:506) ~[?:?]
	at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:135) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:207) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.griefdefender.lib.typesafe.config.ConfigException$Parse: Reader: 169: Expecting a value but got wrong token: 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) (if you intended 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:251) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:473) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:456) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:456) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.Parseable.parseValue(Parseable.java:180) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.Parseable.parseValue(Parseable.java:174) ~[?:?]
	at com.griefdefender.lib.typesafe.config.impl.Parseable.parse(Parseable.java:299) ~[?:?]
	at com.griefdefender.lib.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:622) ~[?:?]
	at com.griefdefender.lib.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:173) ~[?:?]
	at com.griefdefender.lib.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:54) ~[?:?]
	at com.griefdefender.lib.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:137) ~[?:?]
	... 15 more
[16:05:45] [Server thread/WARN]: java.lang.NullPointerException
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.cache.MessageCache.loadCache(MessageCache.java:536)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GriefDefenderPlugin.loadConfig(GriefDefenderPlugin.java:1150)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:570)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:506)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:135)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[16:05:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:207)
[16:05:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[16:05:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[16:05:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:05:45] [Server thread/INFO]: [GriefDefender] Detected Vault. Checking for compatible economy plugin...
[16:05:45] [Server thread/INFO]: [GriefDefender] Found economy plugin 'CMIEconomy'. GriefDefender economy integration is now enabled.
[16:05:45] [Server thread/INFO]: [GriefDefender] Detected PlaceholderAPI. Enabling GD PlaceholderAPI expansion...
[16:05:45] [Server thread/INFO]: [GriefDefender] GriefDefender PlaceholderAPI expansion enabled!
[16:05:45] [Server thread/INFO]: [GriefDefender] Unable to initialize file storage.
[16:05:45] [Server thread/INFO]: [GriefDefender] null
[16:05:45] [Server thread/WARN]: java.lang.NullPointerException
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.storage.BaseStorage.setDefaultGlobalPermissions(BaseStorage.java:361)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.storage.BaseStorage.initialize(BaseStorage.java:112)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.storage.FileStorage.initialize(FileStorage.java:88)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:623)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GriefDefenderPlugin.onEnable(GriefDefenderPlugin.java:506)
[16:05:45] [Server thread/WARN]: 	at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:135)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[16:05:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[16:05:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:207)
[16:05:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[16:05:45] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[16:05:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by D-Jy-lab** [comment]
[zh_CN.zip](https://github.com/bloodmc/GriefDefender/files/5925257/zh_CN.zip)
Fixed language file.

**Comment by ahdg6** [comment]
#369 我对我的疏忽感到抱歉，在修复一些语句问题的同时更改了措辞，希望对您有所帮助。
I'm sorry for my negligence. I changed the wording while fixing some problems in the sentence. I hope it can be helpful to you
