### ISSUE TITLE
Error: Unable to delete claim file

### ISSUE THREAD

**Issue by tak-dev** [bloodmc/GriefDefender#39]
```
[18:07:52] [Server thread/INFO]: PLAYER issued server command: /abandontop
[18:07:52] [Server thread/WARN]: java.nio.file.NoSuchFileException: ./plugins/GriefDefender/worlds/normal/world/ClaimData/basic/ef337928-8b38-4785-ba63-734b3bbd8ce4
[18:07:52] [Server thread/WARN]: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[18:07:52] [Server thread/WARN]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[18:07:52] [Server thread/WARN]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[18:07:52] [Server thread/WARN]: 	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
[18:07:52] [Server thread/WARN]: 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[18:07:52] [Server thread/WARN]: 	at java.nio.file.Files.delete(Files.java:1126)
[18:07:52] [Server thread/WARN]: 	at com.griefdefender.storage.FileStorage.deleteClaimFromStorage(FileStorage.java:457)
[18:07:52] [Server thread/WARN]: 	at com.griefdefender.claim.GDClaimManager.deleteClaimInternal(GDClaimManager.java:319)
[18:07:52] [Server thread/WARN]: 	at com.griefdefender.command.CommandClaimAbandon.execute(CommandClaimAbandon.java:134)
[18:07:52] [Server thread/WARN]: 	at com.griefdefender.command.CommandClaimAbandonTop.execute(CommandClaimAbandonTop.java:46)
[18:07:52] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:07:52] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:07:52] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:07:52] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:07:52] [Server thread/WARN]: 	at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[18:07:52] [Server thread/WARN]: 	at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:576)
[18:07:52] [Server thread/WARN]: 	at co.aikar.commands.BaseCommand.execute(BaseCommand.java:512)
[18:07:52] [Server thread/WARN]: 	at co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[18:07:52] [Server thread/WARN]: 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[18:07:52] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:07:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989)
[18:07:52] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922)
[18:07:52] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:07:52] [Server thread/ERROR]: [GriefDefender] Error: Unable to delete claim file "./plugins/GriefDefender/worlds/normal/world/ClaimData/basic/ef337928-8b38-4785-ba63-734b3bbd8ce4".
```

This is with GriefDefender DEV9.

**Comment by TakoidGit** [comment]
Happened again just now on DEV 14b:
```
[17:07:24] [Server thread/WARN]: java.nio.file.NoSuchFileException: ./plugins/GriefDefender/worlds/normal/world/ClaimData/basic/0bb33c6b-4184-41fb-93b9-b66688438129
[17:07:24] [Server thread/WARN]: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[17:07:24] [Server thread/WARN]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[17:07:24] [Server thread/WARN]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[17:07:24] [Server thread/WARN]: 	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
[17:07:24] [Server thread/WARN]: 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[17:07:24] [Server thread/WARN]: 	at java.nio.file.Files.delete(Files.java:1126)
[17:07:24] [Server thread/WARN]: 	at com.griefdefender.storage.FileStorage.deleteClaimFromStorage(FileStorage.java:457)
[17:07:24] [Server thread/WARN]: 	at com.griefdefender.claim.GDClaimManager.deleteClaimInternal(GDClaimManager.java:319)
[17:07:24] [Server thread/WARN]: 	at com.griefdefender.claim.GDClaimManager.deleteClaim(GDClaimManager.java:275)
[17:07:24] [Server thread/WARN]: 	at com.griefdefender.storage.BaseStorage.deleteClaim(BaseStorage.java:196)
[17:07:24] [Server thread/WARN]: 	at com.griefdefender.command.CommandClaimDelete.lambda$createConfirmationConsumer$0(CommandClaimDelete.java:102)
[17:07:24] [Server thread/WARN]: 	at com.griefdefender.command.CommandCallback.execute(CommandCallback.java:44)
[17:07:24] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
[17:07:24] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:07:24] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:07:24] [Server thread/WARN]: 	at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[17:07:24] [Server thread/WARN]: 	at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:576)
[17:07:24] [Server thread/WARN]: 	at co.aikar.commands.BaseCommand.execute(BaseCommand.java:512)
[17:07:24] [Server thread/WARN]: 	at co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[17:07:24] [Server thread/WARN]: 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[17:07:24] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:07:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990)
[17:07:24] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923)
[17:07:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:07:24] [Server thread/ERROR]: [GriefDefender] Error: Unable to delete claim file "./plugins/GriefDefender/worlds/normal/world/ClaimData/basic/0bb33c6b-4184-41fb-93b9-b66688438129".
```

**Comment by bloodmc** [comment]
Unable to reproduce this with latest builds. Please reopen ticket if it occurs again.
