### ISSUE TITLE
[BUG] Cannot invoke "java.io.File.toPath()" because "file" is null

### ISSUE THREAD

**Issue by Baktus79** [bloodmc/GriefDefender#411]
- **Versions**
Spigot/Paper/Sponge: Paper 132 *(1.17.1)*
GriefDefender: 2.0.0
LuckPerms: 5.3.53

- **Describe the bug**

GriefDefender will not start at startup. See error message further down. Attempted to restart the server, removed the GriefDefender and LuckPerms folder. None of the attempts help.

- **Steps to reproduce the behavior**

1. Put the Griefdefender plugin in the plugin folder.
2. Start the server. 

- **Pluginlist**
CMI _v9.0.1.3_
CMI Lib _v1.0.3.0_
LuckPerms _v5.3.53_
WorldEdit _v7.2.5_

- **Error message**
```[17:59:16] [Server thread/INFO]: [GriefDefender] Enabling GriefDefender v2.0.0
[17:59:16] [Server thread/INFO]: [GriefDefender] Loading libraries...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.griefdefender:adapter:1.17.1-SNAPSHOT ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.griefdefender:reflect-helper:3.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.checkerframework:checker-qual:2.10.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.ow2.asm:asm-commons:9.1 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library co.aikar:acf-core:0.5.0-SNAPSHOT ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library co.aikar:acf-bukkit:0.5.0-SNAPSHOT ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library co.aikar:acf-paper:0.5.0-SNAPSHOT ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library co.aikar:locales:1.0-SNAPSHOT ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library co.aikar:minecraft-timings:1.0.4 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library co.aikar:Table:1.0.0-SNAPSHOT ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library net.jodah:expiringmap:0.5.9 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library aopalliance:aopalliance:1.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.flowpowered:flow-math:1.0.3 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.google.inject:guice:5.0.1 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library javax.inject:javax.inject:1 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.squareup.okhttp3:okhttp:4.7.2 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.squareup.okio:okio:2.6.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.github.ben-manes.caffeine:caffeine:2.7.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library commons-io:commons-io:2.6 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.apache.commons:commons-lang3:3.9 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.spongepowered:configurate-core:4.0.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.spongepowered:configurate-gson:4.0.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.spongepowered:configurate-hocon:4.0.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library org.spongepowered:configurate-yaml:4.0.0 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library io.leangen.geantyref:geantyref:1.3.11 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library com.typesafe:config:1.3.1 ...
[17:59:16] [Server thread/INFO]: [GriefDefender] Downloading library it.unimi.dsi:fastutil:8.2.3 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library org.jetbrains.kotlin:kotlin-stdlib:1.3.72 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-nbt:4.8.0 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-platform-api:4.0.0-SNAPSHOT ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-platform-bukkit:4.0.0-SNAPSHOT ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-platform-bungeecord:4.0.0-SNAPSHOT ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-platform-facet:4.0.0-SNAPSHOT ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-serializer-configurate4:4.8.0 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-text-serializer-craftbukkit:4.0.0-SNAPSHOT ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-text-serializer-gson:4.8.0 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-text-serializer-gson-legacy-impl:4.8.0 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-text-serializer-legacy:4.8.0 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library net.kyori:adventure-text-serializer-plain:4.8.0 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library com.zaxxer:HikariCP:4.0.3 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library mysql:mysql-connector-java:8.0.25 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library org.postgresql:postgresql:42.2.20 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library org.mariadb.jdbc:mariadb-java-client:2.7.3 ...
[17:59:17] [Server thread/INFO]: [GriefDefender] Downloading library org.xerial:sqlite-jdbc:3.34.0 ...
[17:59:17] [Server thread/ERROR]: Error occurred while enabling GriefDefender v2.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "file" is null
	at com.griefdefender.GDBootstrap.injectRelocatorDeps(GDBootstrap.java:167) ~[?:?]
	at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:146) ~[?:?]
	at com.griefdefender.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Paper-132]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[patched_1.17.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[17:59:17] [Server thread/INFO]: [GriefDefender] Disabling GriefDefender v2.0.0
[17:59:17] [Server thread/ERROR]: Error occurred while disabling GriefDefender v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/griefdefender/lib/configurate/util/NamingScheme
	at com.griefdefender.GDBootstrap.onDisable(GDBootstrap.java:160) ~[?:?]
	at com.griefdefender.loader.BukkitLoaderPlugin.onDisable(BukkitLoaderPlugin.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Paper-132]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[patched_1.17.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.griefdefender.lib.configurate.util.NamingScheme
	at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 13 more
```

**Comment by bloodmc** [comment]
Fixed in latest update on spigot.
