### ISSUE TITLE
Exception in command: gd:callback

### ISSUE THREAD

**Issue by tak-dev** [bloodmc/GriefDefender#42]
```
[02:04:59] [Server thread/INFO]: PLAYER issued server command: /gd:callback
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] Exception in command: gd:callback 
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] java.lang.reflect.InvocationTargetException
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:576)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.BaseCommand.execute(BaseCommand.java:512)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at java.lang.Thread.run(Thread.java:748)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	at com.griefdefender.command.CommandCallback.execute(CommandCallback.java:41)
[02:04:59] [Server thread/ERROR]: [GriefDefender] [ACF] 	... 25 more
```

Dev build 14a

**Comment by bloodmc** [comment]
Unable to reproduce this with latest builds. Please reopen ticket if it occurs again.
