### ISSUE TITLE
[BUG] Could not pass event WorldInitEvent to GriefDefender

### ISSUE THREAD

**Issue by brunyman** [bloodmc/GriefDefender#424]
- **Versions**
Spigot/Paper/Sponge: arclight-forge-1.16.5-1.0.20.jar     https://github.com/IzzelAliz/Arclight
GriefDefender: griefdefender-bukkit-2.0.1.jar
LuckPerms: LuckPerms-Bukkit-5.3.47.jar

- **Describe the bug**
Full server log: https://pastebin.com/GDnirreQ
On plugin load the error takes place first time, then every time the server saves world data:
[08Oct2021 13:42:16.117] [Server thread/ERROR] [Minecraft/]: Could not pass event WorldInitEvent to GriefDefender v2.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.20-368b0cb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.20-368b0cb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.20-368b0cb]
	at net.minecraft.server.MinecraftServer.redirect$bdj000$arclight$worldInit(MinecraftServerMixin.java:2017) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:377) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.name()" because "dimType" is null
	at com.griefdefender.storage.BaseStorage.getWorldPath(BaseStorage.java:546) ~[?:?]
	at com.griefdefender.storage.FileStorage.loadWorldData(FileStorage.java:183) ~[?:?]
	at com.griefdefender.internal.util.NMSUtil.onWorldInit(NMSUtil.java:1300) ~[?:?]
	... 10 more

- **Steps to reproduce the behavior**
The error takes place on plugin load and every time the world save tasks runs.

- **Expected behavior**
No error

- **GDDEBUG**

- **Screenshots**

**Comment by ahdg6** [comment]
Can you reproduct it with Arclight-forge-1.16.5/1.0.21-SNAPSHOT? it just works fine for me.

**Comment by brunyman** [comment]
Indeed the error does not show when running it without mods, however when adding the mods in the Direwolf20 1.16.5 mod pack the error is there, my guess is that a mod that generates worlds starts this issue. Can we have a null check there? at current state it spams the server so bad until it rans out of memory and crashes so it's unusable. I believe we can't get the source code to adapt it to our needs?

Thanks!

**Comment by ahdg6** [comment]
You had better ask support in Discord as Hybrid is so complex. Only can bloodmc solve this problem and he is not always active on GitHub.

**Comment by brunyman** [comment]
What Discord?  I guess I will fall back to v1 then, where source code is available and I can patch the error, however it would be nice to be able to use v2 since we payed for it already.

**Comment by ahdg6** [comment]
A Discord link should be sent to your Paypal email address after you paid. I also expect Blood to open source V2.

**Comment by brunyman** [comment]
I only got the paypal payment confirmation on email so no Discord invite. We need to be able to run the plugin on java 16 so we definitely need this patched or the source code of v2

**Comment by brunyman** [comment]
I understand that this could be also Archlight issue, but only happens on GD from our stack of plugins. And we also only use GD claims on the overworld so even if this error breaks all GD events so the plugin will not work in those worlds that's fine for us since we don't even use it for other worlds, so for us a NULL check there will fix the issues created by that error intense spam. Now I would like to have this running on java 16, this is a must for mc 1.17 anyway and rewritting GD v1 seems not fun. I will do some testing just hiding the errors from console and logs with plugin  https://www.spigotmc.org/resources/console-spam-fix.18410/  and see how stable the server is, hopefully it does not freeze the main thread when the errors goes creazy or lower the TPS badly. At least as a temporarily patch to be able to run it, so if someone else have this issue can try this too

**Comment by ahdg6** [comment]
![图片](https://user-images.githubusercontent.com/36436808/136688313-70ec6ed1-5785-40a2-bb12-fc62d433d579.png)

**Comment by brunyman** [comment]
OK, bad news, hiding the messages does help a lot, however to make things weird the error was triggering even for some players in the overworld, means they could not use the claim system at all, or bypass it in the overworld. So time for debug:

```
[10Oct2021 22:40:09.750] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - NORMAL - world - normal
[10Oct2021 22:40:10.128] [Server thread/INFO] [GriefDefender/]: [world] 2 total claims loaded.
[10Oct2021 22:40:10.128] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world...
[10Oct2021 22:40:10.169] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - NETHER - world/dim-1 - nether
[10Oct2021 22:40:10.177] [Server thread/INFO] [GriefDefender/]: [world/dim-1] 0 total claims loaded.
[10Oct2021 22:40:10.177] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/DIM-1...
[10Oct2021 22:40:10.188] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - THE_END - world/dim1 - the_end
[10Oct2021 22:40:10.197] [Server thread/INFO] [GriefDefender/]: [world/dim1] 1 total claims loaded.
[10Oct2021 22:40:10.197] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/DIM1...
[10Oct2021 22:40:10.199] [Server thread/WARN] [Arclight/]: Assign ResourceKey[minecraft:dimension_type / compactmachines:compact_world] to unknown dimension type net.minecraft.world.DimensionType@6897fc17 as {}
[10Oct2021 22:40:10.200] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - null - world/compactmachines/compact_world - null
[10Oct2021 22:40:10.206] [Server thread/ERROR] [Minecraft/]: Could not pass event WorldInitEvent to GriefDefender v2.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-]
	at net.minecraft.server.MinecraftServer.redirect$bdk000$arclight$worldInit(MinecraftServerMixin.java:2017) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:377) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.name()" because "dimType" is null
	at com.griefdefender.storage.FileStorage.registerWorld(FileStorage.java:97) ~[?:?]
	at com.griefdefender.storage.FileStorage.loadWorldData(FileStorage.java:186) ~[?:?]
	at com.griefdefender.internal.util.NMSUtil.onWorldInit(NMSUtil.java:1300) ~[?:?]
	... 10 more
[10Oct2021 22:40:10.212] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - RATS_RATLANTIS - world/rats/ratlantis - rats_ratlantis
[10Oct2021 22:40:10.218] [Server thread/INFO] [GriefDefender/]: [world/rats/ratlantis] 0 total claims loaded.
[10Oct2021 22:40:10.218] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/rats/ratlantis...
[10Oct2021 22:40:10.222] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - TWILIGHTFOREST_FOREST_TYPE - world/twilightforest/forest_type - twilightforest_forest_type
[10Oct2021 22:40:10.230] [Server thread/INFO] [GriefDefender/]: [world/twilightforest/forest_type] 2 total claims loaded.
[10Oct2021 22:40:10.230] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/twilightforest/forest_type...
[10Oct2021 22:40:10.234] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - WOOT_MOBSIMULATOR - world/woot/mobsimulator - woot_mobsimulator
[10Oct2021 22:40:10.240] [Server thread/INFO] [GriefDefender/]: [world/woot/mobsimulator] 0 total claims loaded.
[10Oct2021 22:40:10.241] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/woot/mobsimulator...
[10Oct2021 22:40:10.244] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - TWILIGHTFOREST_FOREST_TYPE - world/twilightforest/forest_type - twilightforest_forest_type
[10Oct2021 22:40:10.252] [Server thread/INFO] [GriefDefender/]: [world/twilightforest/forest_type] 1 total claims loaded.
[10Oct2021 22:40:10.252] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/twilightforest/forest_type...
[10Oct2021 22:40:10.256] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - MYTHICBOTANY_ALFHEIM - world/mythicbotany/alfheim - mythicbotany_alfheim
[10Oct2021 22:40:10.262] [Server thread/INFO] [GriefDefender/]: [world/mythicbotany/alfheim] 0 total claims loaded.
[10Oct2021 22:40:10.262] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/mythicbotany/alfheim...
[10Oct2021 22:40:10.266] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - UNDERGARDEN_UNDERGARDEN - world/undergarden/undergarden - undergarden_undergarden
[10Oct2021 22:40:10.273] [Server thread/INFO] [GriefDefender/]: [world/undergarden/undergarden] 0 total claims loaded.
[10Oct2021 22:40:10.273] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/undergarden/undergarden...
[10Oct2021 22:40:10.276] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - JAVD_VOID - world/javd/void - javd_void
[10Oct2021 22:40:10.283] [Server thread/INFO] [GriefDefender/]: [world/javd/void] 0 total claims loaded.
[10Oct2021 22:40:10.283] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/javd/void...
[10Oct2021 22:40:10.286] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - JAMD_MINING - world/jamd/mining - jamd_mining
[10Oct2021 22:40:10.296] [Server thread/INFO] [GriefDefender/]: [world/jamd/mining] 0 total claims loaded.
[10Oct2021 22:40:10.297] [Server thread/INFO] [GriefDefender/]: Loading schematics for world world/jamd/mining...
```

**This is really interesting:**
```
[10Oct2021 22:40:10.199] [Server thread/WARN] [Arclight/]: Assign ResourceKey[minecraft:dimension_type / compactmachines:compact_world] to unknown dimension type net.minecraft.world.DimensionType@6897fc17 as {}
[10Oct2021 22:40:10.200] [Server thread/INFO] [STDOUT/]: [com.griefdefender.storage.BaseStorage:registerWorld:512]: Debug 1 - null - world/compactmachines/compact_world - null
[10Oct2021 22:40:10.206] [Server thread/ERROR] [Minecraft/]: Could not pass event WorldInitEvent to GriefDefender v2.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-]
	at net.minecraft.server.MinecraftServer.redirect$bdk000$arclight$worldInit(MinecraftServerMixin.java:2017) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:377) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.World$Environment.name()" because "dimType" is null
	at com.griefdefender.storage.FileStorage.registerWorld(FileStorage.java:97) ~[?:?]
	at com.griefdefender.storage.FileStorage.loadWorldData(FileStorage.java:186) ~[?:?]
	at com.griefdefender.internal.util.NMSUtil.onWorldInit(NMSUtil.java:1300) ~[?:?]
	... 10 more
```

Debug being:  System.out.println("Debug 1 - " + dimType + " - " + worldName + " - " + dimName);

**Comment by brunyman** [comment]
So, a temp patch to get it to work, my focus on my needs for overworld, nether and the end worlds was to change this:

```
World.Environment dimType = world.getEnvironment();
     String worldName = world.getName().toLowerCase();
     String dimName = "null";
     if (dimType == null) {
	    if (worldName.matches("world")) {
		    dimName = "normal";
	    } else if (worldName.matches("world/dim-1")) {
	    	dimName = "nether";
	    } else if (worldName.matches("world/dim1")) {
	    	dimName = "the_end";
	    }
    } else {
	    dimName = dimType.name().toLowerCase();
    }
```

**Comment by bloodmc** [comment]
```java
@NotNull
public Environment getEnvironment();
```

This is an arclight issue as `getEnvironment` should never return null according to javadocs. Report to Arclight as there is no issue on Paper/Spigot.

As for discord, if you need another link then send an email to kanesoftware@outlook.com with proof of purchase.
