### ISSUE TITLE
Nether Portal Error Message on Console

### ISSUE THREAD

**Issue by AlterDimension** [bloodmc/GriefDefender#425]
- **Versions**
Spigot/Paper/Sponge: Paper 1.12.2 1618
GriefDefender: 2.0.1
LuckPerms: v5.3.69

- **Describe the bug**
Could not pass portal create event to grief defender shown on console

- **Steps to reproduce the behavior**
1. Claim land
2. Create Nether Portal
3. Lit Nether Portal
4. Error message shown

- **Expected behavior**
I expected it to show no error when portal is lit in a claimed land

- **GDDEBUG**
[18:14:43 ERROR]: Could not pass event PortalCreateEvent to GriefDefender v2.0.1
java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getEntity()Lorg/bukkit/entity/Entity;
at com.griefdefender.listener.PlayerEventHandler.onPlayerPortalCreate(PlayerEventHandler.java:1172) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor54.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.BlockPortal$Shape.createPortal(BlockPortal.java:377) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.BlockPortal.b(BlockPortal.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.BlockFire.onPlace(BlockFire.java:330) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:277) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

- **Screenshots**
![image](https://user-images.githubusercontent.com/65042209/136667610-8c0714e8-1c85-4a64-85e2-a4328d0b877e.png)

**Comment by bloodmc** [comment]
Thanks, will be fixed in 2.0.4

**Comment by AlterDimension** [comment]
Your welcome :)

**Comment by bloodmc** [comment]
Fixed in 2.0.4 release
