### ISSUE TITLE
[BUG] Can't delete and view Claim details

### ISSUE THREAD

**Issue by speccycy** [bloodmc/GriefDefender#427]
- **Versions**
Hybrid: CatServer-d1fba12-universal 1.12.2
GriefDefender: griefdefender-bukkit-2.0.1
LuckPerms: LuckPerms-Bukkit-5.3.70
Database: MariaDB

- **Describe the bug**

Claim Player has a problem. can't delete and unable to view details of this Claim
Claim owner cannot place blocks. but can break blocks

When checking the area with Stick, only one point can be checked. but unable to check the whole area
in spite of the block showing the entire area according to the video seen

And when I use the command `/gd debug Physics` there is an error spam and GD can't work.

**Error log when clicking on Claim details**
```
[18:04:47] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Speccycy issued server command: /gd:callback 65b11783-b865-4da3-8e52-3acf08c3d466
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] Exception in command: gd:callback 65b11783-b865-4da3-8e52-3acf08c3d466
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] java.lang.NullPointerException
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.command.CommandClaimInfo.showGUI(CommandClaimInfo.java:129)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.text.GuiHelper.lambda$createClaimInfoReturnConsumer$1(GuiHelper.java:300)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.command.CommandCallback.execute(CommandCallback.java:47)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.lib.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.lib.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:577)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.lib.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.lib.aikar.commands.RootCommand.execute(RootCommand.java:99)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at com.griefdefender.lib.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:710)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1650)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1451)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685)
 
[18:04:47] [Server thread/ERROR] [GriefDefender]: [ACF] 	at java.lang.Thread.run(Thread.java:748)
```

**spam error when I use the /gd debug physics command**
```
[17:15:49] [Server thread/ERROR] [Minecraft]: Could not pass event ChunkUnloadEvent to GriefDefender v2.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-d1fba12]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-d1fba12]
	at net.minecraft.world.gen.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:313) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:288) [on.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:308) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:951) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.NullPointerException
```

- **Steps to reproduce the behavior**

1. Use Stick to check the Claim, press to see details of the area. Can't see the details, showing error message
2. Use command /gd delete claim deleted but Claim still returned like
3. Use the command /gd debug Physic.

- **Expected behavior**

- **Screenshots**

https://cdn.discordapp.com/attachments/836712558483734598/899266085449269268/Minecraft_1.12.2_2564-10-17_17-54-08_Trim.mp4

**Comment by speccycy** [comment]
Player Abandon Claim now
But the Claim was not removed, and the area's details were still not available.

**Comment by bloodmc** [comment]
This does not happen on Paper. Open a ticket with CatServer.
