### ISSUE TITLE
[BUG] Error Detected invalid hash

### ISSUE THREAD

**Issue by thiagogebrimm** [bloodmc/GriefDefender#452]
- **Versions**
Spigot/Paper/Sponge:  Purpur 1612
GriefDefender: 2.1.5
LuckPerms: 5.4.21

- **Describe the bug**
```
[22:20:44 INFO]: [GriefDefender] Enabling GriefDefender v2.1.5
[22:20:44 INFO]: [GriefDefender] Loading libraries...
[22:20:44 INFO]: [GriefDefender] Downloading library it.unimi.dsi:fastutil:8.2.3 ...
[22:20:46 ERROR]: [GriefDefender] Detected invalid hash 'a909be14466e5a1a3f7a1cf3aa679b3af6a10664' for file './plugins/GriefDefender/lib/it/unimi/dsi/fastutil/8.2.3/fastutil-8.2.3.jar'. Expected 'f3a26db2204f1779c9958a914422f84284e53a84'. Skipping...
[22:20:46 INFO]: [GriefDefender] Downloading library org.jetbrains.kotlin:kotlin-stdlib:1.3.72 ...
[22:22:58 ERROR]: [GriefDefender] An error occured while downloading library 'org.jetbrains.kotlin:kotlin-stdlib:1.3.72'. Skipping...
[22:22:58 WARN]: java.net.ConnectException: Connection timed out
[22:22:58 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[22:22:58 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[22:22:58 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[22:22:58 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[22:22:58 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[22:22:58 WARN]:        at java.base/java.net.Socket.connect(Socket.java:639)
[22:22:58 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[22:22:58 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[22:22:58 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[22:22:58 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[22:22:58 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1245)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1131)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1668)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
[22:22:58 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[22:22:58 WARN]:        at com.griefdefender.GDBootstrap.downloadLibrary(GDBootstrap.java:189)
[22:22:58 WARN]:        at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:144)
[22:22:58 WARN]:        at griefdefender-bukkit-2.1.5.jar//com.griefdefender.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:48)
[22:22:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:22:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:22:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535)
[22:22:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[22:22:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[22:22:58 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:324)
[22:22:58 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[22:22:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[22:22:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

- **Steps to reproduce the behavior**
Just launch the plugin

**Comment by bloodmc** [comment]
Hash is correct. You are using a modified jar.
https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/8.2.3/fastutil-8.2.3.jar.sha1

**Comment by thiagogebrimm** [comment]
I'm using the spigot jar '-' I downloaded it yesterday

**Comment by thiagogebrimm** [comment]
I try download one more time and got a new error
```
[15:38:05 ERROR]: [GriefDefender] An error occured while downloading library 'org.checkerframework:checker-qual:2.10.0'. Skipping...
[15:38:05 WARN]: java.net.ConnectException: Connection timed out
[15:38:05 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[15:38:05 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[15:38:05 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[15:38:05 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[15:38:05 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[15:38:05 WARN]:        at java.base/java.net.Socket.connect(Socket.java:639)
[15:38:05 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[15:38:05 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[15:38:05 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[15:38:05 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[15:38:05 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1245)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1131)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1668)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
[15:38:05 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[15:38:05 WARN]:        at com.griefdefender.GDBootstrap.downloadLibrary(GDBootstrap.java:189)
[15:38:05 WARN]:        at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:144)
[15:38:05 WARN]:        at griefdefender-bukkit-2.1.5.jar//com.griefdefender.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:48)
[15:38:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:38:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:38:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535)
[15:38:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[15:38:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[15:38:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:324)
[15:38:05 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[15:38:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[15:38:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by bloodmc** [comment]
I see now…GD needs access to the internet to download the libraries it uses. Your connection is either not working or is blocking external access.

**Comment by thiagogebrimm** [comment]
Yes, I think it's the anti-ddos block, can you tell me the ip for me to release?

**Comment by bloodmc** [comment]
If you open the jar with any zip program, you will see JSON files. These files are what determine what URL is used to download each library. Simply open the JSON that corresponds to your MC version and edit the URLs to another maven you can access.
