### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ga6rielsilva** [bloodmc/GriefDefender#473]
- **Versions**
Spigot/Paper/Sponge: 
![image](https://user-images.githubusercontent.com/62969752/190040441-f19b312a-9b27-4fbb-950c-64e42272601f.png)
GriefDefender: 2.2.3
LuckPerms: 5.4.46

- **Describe the bug**

Every time I break a block, the block drop triggers an error message on the console.
```console
[22:58:34 ERROR]: Could not pass event ItemSpawnEvent to GriefDefender v2.2.2
 java.lang.NoSuchFieldError: COMMAND
	at com.griefdefender.listener.EntityEventHandler.handleEntitySpawn(EntityEventHandler.java:775) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onItemSpawn(EntityEventHandler.java:705) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:408) ~[CraftEventFactory.class:?]
	at net.minecraft.world.World.addEntity(World.java:1502) ~[amu.class:?]
	at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1251) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1245) ~[oo.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:505) ~[ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71040_bB(EntityPlayer.java:724) ~[aed.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1054) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_341]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_341]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
```

- **Steps to reproduce the behavior**

Breaking any block

- **Expected behavior**

Fix It

- **GDDEBUG**

Nop

- **Screenshots**

Nop

**Comment by ahdg6** [comment]
Had been fixed on v2.2.4, grab it on discord.
