### ISSUE TITLE
[BUG] Can not open claimflag inventory gui

### ISSUE THREAD

**Issue by madic-creates** [bloodmc/GriefDefender#479]
- **Versions**
Spigot/Paper/Sponge: 1.19.2 Paper 298
GriefDefender: 2.3.0
LuckPerms: 5.4.54

When enabling the gui via /claimgui and opening /claimflag, I am not able to click on the icons for admin or user flags.
Upon clicking the icon, the following error occurs in the server log:

```[00:46:18 ERROR]: Could not pass event InventoryClickEvent to GriefDefender v2.3.0
java.lang.NullPointerException: Cannot invoke "com.griefdefender.api.gui.Icon.getLore()" because "icon" is null
        at com.griefdefender.gui.inventory.InventoryGuiFlag.loadFlagGroupTypeMenu(InventoryGuiFlag.java:288) ~[?:?]
        at com.griefdefender.gui.inventory.InventoryGuiFlag.lambda$loadFlagGroupMenu$14(InventoryGuiFlag.java:235) ~[?:?]
        at com.griefdefender.lib.triumphteam.gui.guis.GuiListener.onGuiClick(GuiListener.java:102) ~[griefdefender-bukkit-2.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor538.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-298]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3307) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-298]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-298]
        at java.lang.Thread.run(Unknown Source) ~[?:?]```

**Comment by madic-creates** [comment]
Removing gui.conf as mentioned today on discord fixed the problem
