### ISSUE TITLE
TIMING_STACK_CORRUPTION NPE

### ISSUE THREAD

**Issue by tak-dev** [bloodmc/GriefDefender#48]
```
[17:12:34] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to the plugin GriefDefender(Look for errors above this in the logs) (TimingIdentifier{id=GriefDefender:onEntityExplosionPre} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-175]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-175]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[patched_1.14.4.jar:git-Paper-175]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:203) ~[patched_1.14.4.jar:git-Paper-175]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.EntityCreeper.explode(EntityCreeper.java:212) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.EntityCreeper.tick(EntityCreeper.java:120) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:431) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

Release 1.2.1.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/14c087c950e92c6a0c893f79eea82a8200bb874d
