### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wkurumi** [bloodmc/GriefDefender#483]
- **Versions**
Spigot/Paper/Sponge: pufferfish1.19.2
GriefDefender: griefdefender-bukkit-2.3.0
LuckPerms: LuckPerms-Bukkit-5.4.40

- **Describe the bug**

- **Steps to reproduce the behavior**

- **Expected behavior**

[17:36:42] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to GriefDefender v2.3.0
java.lang.IllegalArgumentException: name cannot be empty!
	at com.griefdefender.api.permission.Context.<init>(Context.java:61) ~[griefdefender-bukkit-2.3.0.jar:?]
	at com.griefdefender.permission.GDPermissionManager.addCustomEntityTypeContexts(GDPermissionManager.java:1396) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getPermissionContexts(GDPermissionManager.java:996) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:276) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:219) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.handleEntitySpawn(EntityEventHandler.java:909) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onCreatureSpawn(EntityEventHandler.java:700) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-46]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:740) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:645) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1493) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1401) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.addEntityToWorld(CraftWorld.java:1062) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.addEntity(CraftRegionAccessor.java:536) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:512) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:506) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:497) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at com.magmaguy.elitemobs.utils.VisualArmorStand.VisualArmorStand(VisualArmorStand.java:13) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.npcs.chatter.NPCChatBubble.<init>(NPCChatBubble.java:35) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.npcs.NPCEntity.sayGreeting(NPCEntity.java:282) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.npcs.chatter.NPCProximitySensor$1.run(NPCProximitySensor.java:60) ~[EliteMobs.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1475) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

- **GDDEBUG**

- **Screenshots**

**Comment by wkurumi** [comment]
em_adventurers_guild

**Comment by wkurumi** [comment]
The error may be caused by the [em_adventors_guide] world of [EliteMobs].

**Comment by wkurumi** [comment]
error： [GDHooks] Plugin GDHooks v0.8-DEV has failed to register events for class com.griefdefender.hooks.provider.EliteMobsProvider because com/magmaguy/elitemobs/mobconstructor/EliteMobEntity does not exist.

[GDHooks] also reports an error about [EliteMobs]

**Comment by wkurumi** [comment]
![image](https://user-images.githubusercontent.com/63358787/205553138-0c03f991-2027-4d51-8f70-887cde85d5dd.png)
This will solve the problem.
