### ISSUE TITLE
[BUG] IllegalArgumentException

### ISSUE THREAD

**Issue by nhanledev** [bloodmc/GriefDefender#484]
- **Versions**
Spigot/Paper/Sponge: Paper 1.19.2 Build 300
GriefDefender: v2.3.1-DEV2
LuckPerms: LuckPerms-Bukkit-5.4.54

- **Describe the bug**

The console spam a lot of exception about IllegalArgumentException, this is a few sample of it

```
[11:43:46] [Server thread/ERROR]: Could not pass event EntityTargetLivingEntityEvent to GriefDefender v2.3.1-DEV2
java.lang.IllegalArgumentException: name cannot be empty!
	at com.griefdefender.api.permission.Context.<init>(Context.java:61) ~[griefdefender-bukkit-2.3.1-DEV2.jar:?]
	at com.griefdefender.permission.GDPermissionManager.addCustomEntityTypeContexts(GDPermissionManager.java:1396) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getPermissionContexts(GDPermissionManager.java:996) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:268) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:219) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:206) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onEntityTarget(EntityEventHandler.java:969) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor89.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:279) ~[?:?]
	at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.start(NearestAttackableTargetGoal.java:71) ~[?:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.start(WrappedGoal.java:39) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:137) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:870) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3341) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:640) ~[?:?]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:268) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2992) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:238) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1193) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[13:09:45] [Server thread/ERROR]: Could not pass event EntityChangeBlockEvent to GriefDefender v2.3.1-DEV2
java.lang.IllegalArgumentException: name cannot be empty!
	at com.griefdefender.api.permission.Context.<init>(Context.java:61) ~[griefdefender-bukkit-2.3.1-DEV2.jar:?]
	at com.griefdefender.permission.GDPermissionManager.addCustomEntityTypeContexts(GDPermissionManager.java:1396) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getPermissionContexts(GDPermissionManager.java:996) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:268) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:219) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onEntityChangeBlockEvent(EntityEventHandler.java:199) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1310) ~[paper-1.19.2.jar:git-Paper-300]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1302) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.world.entity.ai.behavior.HarvestFarmland.tick(HarvestFarmland.java:105) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.HarvestFarmland.d(HarvestFarmland.java:28) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:74) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.world.entity.ai.behavior.GateBehavior.tick(GateBehavior.java:67) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:74) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:430) ~[?:?]
	at net.minecraft.world.entity.ai.Brain.tick(Brain.java:375) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:250) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:247) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:881) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3341) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:640) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2992) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.tick(Villager.java:292) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1193) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[17:00:02] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to GriefDefender v2.3.1-DEV2
java.lang.IllegalArgumentException: name cannot be empty!
	at com.griefdefender.api.permission.Context.<init>(Context.java:61) ~[griefdefender-bukkit-2.3.1-DEV2.jar:?]
	at com.griefdefender.permission.GDPermissionManager.addCustomEntityTypeContexts(GDPermissionManager.java:1396) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getPermissionContexts(GDPermissionManager.java:996) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:276) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:219) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:215) ~[?:?]
	at com.griefdefender.listener.PlayerEventHandler.onPlayerInteractEntity(PlayerEventHandler.java:839) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2914) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2970) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2906) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[19:16:56] [Server thread/ERROR]: Could not pass event PotionSplashEvent to GriefDefender v2.3.1-DEV2
java.lang.IllegalArgumentException: name cannot be empty!
	at com.griefdefender.api.permission.Context.<init>(Context.java:61) ~[griefdefender-bukkit-2.3.1-DEV2.jar:?]
	at com.griefdefender.permission.GDPermissionManager.addCustomEntityTypeContexts(GDPermissionManager.java:1396) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getPermissionContexts(GDPermissionManager.java:996) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:276) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:219) ~[?:?]
	at com.griefdefender.listener.CommonEntityEventHandler.protectEntity(CommonEntityEventHandler.java:355) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onPotionDamage(EntityEventHandler.java:464) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onEntityDamage(EntityEventHandler.java:424) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:802) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.world.entity.projectile.ThrownPotion.applySplash(ThrownPotion.java:204) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrownPotion.splash(ThrownPotion.java:118) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrownPotion.onHit(ThrownPotion.java:102) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:79) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1193) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[19:21:56] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to GriefDefender v2.3.1-DEV2
java.lang.IllegalArgumentException: name cannot be empty!
	at com.griefdefender.api.permission.Context.<init>(Context.java:61) ~[griefdefender-bukkit-2.3.1-DEV2.jar:?]
	at com.griefdefender.permission.GDPermissionManager.addCustomEntityTypeContexts(GDPermissionManager.java:1396) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getPermissionContexts(GDPermissionManager.java:996) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:276) ~[?:?]
	at com.griefdefender.permission.GDPermissionManager.getFinalPermission(GDPermissionManager.java:219) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.handleEntitySpawn(EntityEventHandler.java:909) ~[?:?]
	at com.griefdefender.listener.EntityEventHandler.onCreatureSpawn(EntityEventHandler.java:700) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor79.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:740) ~[paper-1.19.2.jar:git-Paper-300]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:645) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1478) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1386) ~[?:?]
	at net.minecraft.world.entity.Mob.convertTo(Mob.java:1406) ~[?:?]
	at net.minecraft.world.entity.monster.ZombieVillager.finishConversion(ZombieVillager.java:230) ~[?:?]
	at net.minecraft.world.entity.monster.ZombieVillager.tick(ZombieVillager.java:154) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1193) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

And some timing stack corrupt

```
[19:21:56] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to the plugin GriefDefender (Look for errors above this in the logs) (TimingIdentifier{id=GriefDefender:onEntitySpawn} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:132) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:96) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:202) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:79) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:740) ~[paper-1.19.2.jar:git-Paper-300]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:645) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1478) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1386) ~[?:?]
	at net.minecraft.world.entity.Mob.convertTo(Mob.java:1406) ~[?:?]
	at net.minecraft.world.entity.monster.ZombieVillager.finishConversion(ZombieVillager.java:230) ~[?:?]
	at net.minecraft.world.entity.monster.ZombieVillager.tick(ZombieVillager.java:154) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1193) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

- **Steps to reproduce the behavior**

Update to v2.3.1-DEV2

- **Expected behavior**

Nothing should be threw

- **GDDEBUG**

- **Screenshots**

**Comment by nhanledev** [comment]
I really don't know what is causing the issue, it only happens if there are a lot of players are playing on my server. That's why I don't know how to reproduce any of this error.
