### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bronzwar** [bloodmc/GriefDefender#486]
- **Versions**
Spigot/Paper/Sponge: 1/18/2
GriefDefender: 2.3.1
LuckPerms: no

- **Describe the bug**

[01:08:13 ERROR]: Could not load 'plugins/griefdefender-bukkit-2.3.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [LuckPerms]. Please download and install these plugins to run 'GriefDefender'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[ssspigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[ssspigot-1.18.2.jar:SSSpigot2-1.18.2-20220925-80b5528]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[ssspigot-1.18.2.jar:SSSpigot2-1.18.2-20220925-80b5528]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[ssspigot-1.18.2.jar:SSSpigot2-1.18.2-20220925-80b5528]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[ssspigot-1.18.2.jar:SSSpigot2-1.18.2-20220925-80b5528]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

- **Steps to reproduce the behavior**

- **Expected behavior**

- **GDDEBUG**

- **Screenshots**

**Comment by Bronzwar** [comment]
i did't use LP

**Comment by Bronzwar** [comment]
you wrote it like "Recommended Plugins"

**Comment by zThana** [comment]
That's a mistake, as [it's a hard dependency](https://github.com/bloodmc/GriefDefender/blob/master/bukkit/src/main/resources/plugin.yml#L4). GriefDefender won't run without LuckPerms.

**Comment by DrWurzeli** [comment]
depend: A list of plugins that your plugin requires to load.
I know this is an older issue, so might have been added in the meantime: on both spigotmc page and https://docs.griefdefender.com/wiki/#requirements it says LP is a requirement and GD will not launch without it.
happy to hear though you were able to figure out the error cause 👍
