### ISSUE TITLE
[BUG]Claimflag interactive menu/inventory not working

### ISSUE THREAD

**Issue by OnevolutionZ** [bloodmc/GriefDefender#505]
- **Versions**
Spigot/Paper/Sponge: Java-Paper build 68 1.20.1
GriefDefender: 2.3.9
LuckPerms: 5.4.102

- **Describe the bug**

Upon typing as the owner of the server will full powers /claimflag, the claimflag interface gets open. After that I try to select admin group via left clicking the golden apple icon named admin, but the claimflag interface for said group in the claim where I am standing will not activate
In the console this error will show upon doing the steps mentioned before:

[22:04:26 ERROR]: Could not pass event InventoryClickEvent to GriefDefender v2.3.9
java.lang.NullPointerException: Cannot invoke "com.griefdefender.api.gui.Icon.getLore()" because "icon" is null
        at com.griefdefender.gui.inventory.InventoryGuiFlag.loadFlagGroupTypeMenu(InventoryGuiFlag.java:347) ~[?:?]
        at com.griefdefender.gui.inventory.InventoryGuiFlag.lambda$loadFlagGroupMenu$14(InventoryGuiFlag.java:290) ~[?:?]
        at com.griefdefender.lib.triumphteam.gui.guis.GuiListener.onGuiClick(GuiListener.java:102) ~[griefdefender-bukkit-2.3.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor660.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-68]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-68]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3198) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

- **Steps to reproduce the behavior**

1-Join the server
2-Type /claimflag, select either of the claimflag groups in the claimflag group selector interface being the groups represented with a golden apple and an apple icon.
3-Watch as the claimflag interface will not show up and getting the error mentioned in the **Describe the bug** section

- **Expected behavior**

I expected the claimflag group interface to be interactive and not show the error so I can as an owner access the claimflag admin interface to modify a flag in a claim

- **GDDEBUG**

- **Screenshots**

![2023-08-16_00 14 10](https://github.com/bloodmc/GriefDefender/assets/122491580/bf89e5f8-c3bc-4820-a752-3aad99de75af)
![grief defender issue](https://github.com/bloodmc/GriefDefender/assets/122491580/aa94a415-1aea-4505-bafa-c447e2023e4e)

**Comment by bloodmc** [comment]
This was an old bug. Deleting gui.conf solves it.
