### ISSUE TITLE
[BUG] NoSuchFieldError: Grass

### ISSUE THREAD

**Issue by kieranlee999** [bloodmc/GriefDefender#511]
Grief Defender - 2.4.7
Spigot on Ubuntu Server

When trying to abandon claim I am getting the following error: 

`[19:02:09] [Server thread/INFO]: M6AYW issued server command: /griefdefender
[19:02:12] [pool-12-thread-2/WARN]: Exception in thread "pool-12-thread-2" java.lang.NoSuchFieldError: GRASS
[19:02:12] [pool-12-thread-2/WARN]:     at com.griefdefender.gui.inventory.InventoryGui.sendConfirmMenu(InventoryGui.java:699)
[19:02:12] [pool-12-thread-2/WARN]:     at com.griefdefender.GriefDefenderPlugin.lambda$sendMessage$24(GriefDefenderPlugin.java:2048)
[19:02:12] [pool-12-thread-2/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:02:12] [pool-12-thread-2/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:02:12] [pool-12-thread-2/WARN]:     at java.base/java.lang.Thread.run(Thread.java:840)`

We are able to make the claim but in order to delete it it has to be done manually through SSH on the server.

**Comment by kieranlee999** [comment]
I think Line 84 needs to be changed to short_grass 
 https://github.com/bloodmc/GriefDefender/blob/e281231d874d78def944e748f6b49057a516b3db/bukkit/src/main/java/com/griefdefender/permission/flag/FlagContexts.java#L84

**Comment by bloodmc** [comment]
Source is no longer updated. This is not an issue with latest builds.
